package br.com.snowcia.reservation;

public enum ReservationServiceType {
    HOSTING_24H,
    DAYCARE_HALF_DAY,
    DAYCARE_FULL_DAY,
    DAYCARE_EXTRA_HOUR,
    DAYCARE_EXTRA_WALK,
    WALK_20_MIN,
    CAT_SITTER_DAILY,
    CAT_SITTER_ADDITIONAL_CAT,
    CAT_SITTER_EXTRA_VISIT,
    MONTHLY_DAYCARE_2X,
    MONTHLY_DAYCARE_3X,
    MONTHLY_DAYCARE_5X,
    MONTHLY_WALKS_2X,
    MONTHLY_WALKS_3X,
    MONTHLY_WALKS_5X
}
